import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PGlite } from "@electric-sql/pglite";
import { pgcrypto } from "@electric-sql/pglite/contrib/pgcrypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const USER_A = "33333333-3333-4333-8333-333333333333";
const USER_B = "44444444-4444-4444-8444-444444444444";
const RUN_ID = "55555555-5555-4555-8555-555555555555";
const UPDATED_AT = "2026-08-19T03:36:02.892Z";
const SOURCE_CHECKSUM = "b".repeat(64);
let db: PGlite;
let liveChecksum: string;

const state = {
  account: { currentBalance: 11956, warningThreshold: 9000 },
  events: [
    { id: "settled", label: "Invented settled", amount: -100, actualAmount: null, date: "2026-07-01", category: "Bills", notes: "", scenarioId: null, isSettled: true },
    { id: "overdue", label: "Visa + VFS", amount: -3500, actualAmount: null, date: "2026-06-08", category: "Travel", notes: "", scenarioId: null, isSettled: false },
    { id: "future-income", label: "Invented income", amount: 2000, actualAmount: null, date: "2026-09-01", category: "Income", notes: "", scenarioId: null, isSettled: false },
    { id: "future-expense", label: "Invented expense", amount: -500, actualAmount: null, date: "2026-09-02", category: "Housing", notes: "Generated by Invented recurring", scenarioId: "plan-a", isSettled: false },
  ],
  scenarios: [{ id: "plan-a", name: "Invented plan", description: "Fixture", isIncluded: true }],
  templates: [{ id: "template-a", type: "recurring", label: "Invented recurring", startMonth: "2026-09", endMonth: "2026-10", items: [] }],
  bucketTemplates: [],
  buckets: { "2026-07": { Bills: { budgeted: 200, isActive: true, entries: [{ id: "bucket-a", amount: 80, date: "2026-07-02", note: "Fixture" }] } } },
  ui: { history: [] },
  meta: {},
};

async function migration(name: string): Promise<string> {
  return readFile(resolve(process.cwd(), `../supabase/migrations/${name}`), "utf8");
}

async function apply(userId = USER_A, email = "owner@example.test", checksum?: string, runId = RUN_ID) {
  return db.query<{ result: Record<string, unknown> }>(`
    select runway_migration.apply_phase4_cutover($1,$2,$3,$4,$5,$6,'2026-08-19') as result
  `, [userId, email, checksum ?? liveChecksum, SOURCE_CHECKSUM, UPDATED_AT, runId]);
}

beforeAll(async () => {
  db = new PGlite({ extensions: { pgcrypto } });
  await db.exec(`
    create role anon nologin;
    create role authenticated nologin;
    create role service_role nologin bypassrls;
    create schema auth;
    create table auth.users (id uuid primary key, email text);
    create function auth.uid() returns uuid language sql stable
      as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
    create schema extensions;
    create table public.runway_state (
      user_id uuid primary key references auth.users (id), state jsonb not null, updated_at timestamptz not null
    );
  `);
  const phase2 = await migration("20260819060132_phase_2_ledger_core.sql");
  await db.exec(phase2);
  await db.exec(await migration("20260819060415_phase_2_view_privileges.sql"));
  await db.exec(await migration("20260819060530_phase_2_fk_indexes.sql"));
  await db.exec(await migration("20260819063329_phase_3_migration_staging.sql"));
  await db.exec(await migration("20260819063626_phase_3_staging_fk_indexes.sql"));
  await db.exec(await migration("20260819114938_phase_4_actual_money_workflows.sql"));
  await db.exec(await migration("20260819115028_phase_4_fk_indexes.sql"));
  await db.query("insert into auth.users (id,email) values ($1,$2),($3,$4)", [USER_A, "owner@example.test", USER_B, "second@example.test"]);
  await db.query("insert into public.runway_state (user_id,state,updated_at) values ($1,$2,$3),($4,$5,$3)", [USER_A, state, UPDATED_AT, USER_B, state]);
  const checksum = await db.query<{ checksum: string }>("select encode(extensions.digest(state::text,'sha256'),'hex') as checksum from public.runway_state where user_id=$1", [USER_A]);
  liveChecksum = checksum.rows[0]!.checksum;
});

afterAll(async () => db.close());

describe.sequential("Phase 4 authoritative cutover", () => {
  it("applies one exact opening transaction and non-authoritative planning data", async () => {
    const result = await apply();
    expect(result.rows[0]!.result).toMatchObject({ forecast_count: 2, historical_settled_count: 1, excluded_overdue_count: 1, scenario_count: 1, already_applied: false });
    const baseline = await db.query<{ balance: number; net_worth: number; opening_count: number }>(`
      select b.display_balance_minor::int as balance, nw.net_worth_minor::int as net_worth,
        (select count(*)::int from public.transactions where user_id=$1 and kind='opening_balance') as opening_count
      from public.account_balances b join public.current_net_worth nw on nw.user_id=b.user_id and nw.currency=b.currency
      join public.accounts a on a.id=b.account_id where b.user_id=$1 and a.is_system=false
    `, [USER_A]);
    expect(baseline.rows[0]).toEqual({ balance: 1195600, net_worth: 1195600, opening_count: 1 });
  });

  it("is idempotent and does not duplicate the opening balance", async () => {
    const rerun = await apply();
    expect(rerun.rows[0]!.result).toMatchObject({ already_applied: true, forecast_count: 2 });
    const counts = await db.query<{ openings: number; forecasts: number }>(`
      select (select count(*)::int from public.transactions where user_id=$1 and kind='opening_balance') openings,
        (select count(*)::int from public.forecast_items where user_id=$1) forecasts
    `, [USER_A]);
    expect(counts.rows[0]).toEqual({ openings: 1, forecasts: 2 });
  });

  it("keeps settled and resolved-overdue events out of both ledger activity and active forecast", async () => {
    const ledger = await db.query<{ legacy_count: number }>("select count(*)::int legacy_count from public.transactions where user_id=$1 and legacy_source_id is not null", [USER_A]);
    expect(ledger.rows[0]!.legacy_count).toBe(0);
    const excluded = await db.query<{ active: number; history: number }>(`
      select (select count(*)::int from public.forecast_items where user_id=$1 and legacy_source_id='overdue') active,
        (select count(*)::int from public.legacy_history_items where user_id=$1 and legacy_source_id in ('settled','overdue')) history
    `, [USER_A]);
    expect(excluded.rows[0]).toEqual({ active: 0, history: 2 });
  });

  it("proves forecast rows do not affect actual balances", async () => {
    await db.exec("set role authenticated");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [USER_A]);
    await db.query("update public.forecast_items set amount_minor=99999999 where legacy_source_id='future-expense'");
    const balance = await db.query<{ balance: number }>("select display_balance_minor::int balance from public.account_balances where user_id=$1 and account_id in (select id from public.accounts where user_id=$1 and not is_system)", [USER_A]);
    await db.exec("reset role");
    expect(balance.rows[0]!.balance).toBe(1195600);
  });

  it("blocks a wrong checksum and a wrong Auth owner", async () => {
    await expect(apply(USER_B, "second@example.test", "0".repeat(64), "66666666-6666-4666-8666-666666666666")).rejects.toThrow(/checksum changed/i);
    await expect(apply(USER_B, "owner@example.test", liveChecksum, "77777777-7777-4777-8777-777777777777")).rejects.toThrow(/identity/i);
  });

  it("creates no normalized records for the excluded second user", async () => {
    const counts = await db.query<{ profiles: number; accounts: number; transactions: number; forecasts: number }>(`
      select (select count(*)::int from public.profiles where user_id=$1) profiles,
        (select count(*)::int from public.accounts where user_id=$1) accounts,
        (select count(*)::int from public.transactions where user_id=$1) transactions,
        (select count(*)::int from public.forecast_items where user_id=$1) forecasts
    `, [USER_B]);
    expect(counts.rows[0]).toEqual({ profiles: 0, accounts: 0, transactions: 0, forecasts: 0 });
  });

  it("records a bank snapshot and creates only an explicitly confirmed reconciliation adjustment", async () => {
    const account = await db.query<{ id: string }>("select id from public.accounts where user_id=$1 and not is_system", [USER_A]);
    await db.exec("set role authenticated");
    await db.query("select set_config('request.jwt.claim.sub',$1,false)", [USER_A]);
    const result = await db.query<{ result: Record<string, unknown> }>(`
      select public.reconcile_account($1,1200000,'2026-08-19T14:00:00Z','Fixture bank observation',true,'fixture-reconciliation') result
    `, [account.rows[0]!.id]);
    await db.exec("reset role");
    expect(result.rows[0]!.result).toMatchObject({ ledger_balance_minor: 1195600, observed_balance_minor: 1200000, difference_minor: 4400 });
    const verified = await db.query<{ balance: number; snapshots: number; adjustments: number }>(`
      select (select display_balance_minor::int from public.account_balances where account_id=$1) balance,
        (select count(*)::int from public.account_balance_snapshots where account_id=$1) snapshots,
        (select count(*)::int from public.transactions where user_id=$2 and kind='adjustment') adjustments
    `, [account.rows[0]!.id, USER_A]);
    expect(verified.rows[0]).toEqual({ balance: 1200000, snapshots: 1, adjustments: 1 });
  });
});
