import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { PGlite } from "@electric-sql/pglite";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
const USER_A="71717171-7171-4717-8717-717171717171",USER_B="72727272-7272-4727-8727-727272727272";
const files=["20260819060132_phase_2_ledger_core.sql","20260819060415_phase_2_view_privileges.sql","20260819060530_phase_2_fk_indexes.sql","20260819063329_phase_3_migration_staging.sql","20260819063626_phase_3_staging_fk_indexes.sql","20260819114938_phase_4_actual_money_workflows.sql","20260819115028_phase_4_fk_indexes.sql","20260819160000_phase_5_forecast_recurrence.sql","20260819190000_phase_6_funds_payday_budgets.sql","20260819190500_phase_6_budget_group_scope_fix.sql","20260819200000_phase_6_1_budget_and_function_cleanup.sql","20260819210000_phase_7_plans_scenarios.sql","20260819210500_phase_7_rpc_exposure_fix.sql"];
let db:PGlite,accountA:string,accountB:string,ruleA:string,ruleB:string,planA:string;
async function asUser<T>(user:string,action:()=>Promise<T>){await db.exec("set role authenticated");await db.query("select set_config('request.jwt.claim.sub',$1,false)",[user]);try{return await action();}finally{await db.exec("reset role");}}
beforeAll(async()=>{db=new PGlite();await db.exec(`create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;create schema auth;create table auth.users(id uuid primary key);create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create schema extensions;`);for(const file of files){let sql=await readFile(resolve(process.cwd(),`../supabase/migrations/${file}`),"utf8");sql=sql.replace("create extension if not exists pgcrypto with schema extensions;","-- pre-provisioned");await db.exec(sql);}await db.query("insert into auth.users(id)values($1),($2)",[USER_A,USER_B]);await db.query("insert into public.profiles(user_id,base_currency,timezone,operating_floor_minor)values($1,'NOK','Europe/Oslo',900000),($2,'NOK','UTC',0)",[USER_A,USER_B]);accountA=(await asUser(USER_A,()=>db.query<{id:string}>("select public.create_account('Operating A','asset','checking','NOK',true,'operating','ledger',null,1195600,now(),'Opening','p7-a') id"))).rows[0]!.id;accountB=(await asUser(USER_B,()=>db.query<{id:string}>("select public.create_account('Operating B','asset','checking','NOK',true,'operating','ledger',null,500000,now(),'Opening','p7-b') id"))).rows[0]!.id;ruleA=(await db.query<{id:string}>("insert into public.recurring_rules(user_id,kind,label,destination_account_id,amount_minor,frequency,day_of_month,start_on,is_reliable_income)values($1,'income','Salary A',$2,3000000,'monthly',1,'2026-09-01',true)returning id",[USER_A,accountA])).rows[0]!.id;ruleB=(await db.query<{id:string}>("insert into public.recurring_rules(user_id,kind,label,destination_account_id,amount_minor,frequency,day_of_month,start_on)values($1,'income','Salary B',$2,2000000,'monthly',1,'2026-09-01')returning id",[USER_B,accountB])).rows[0]!.id;planA=(await db.query<{id:string}>("insert into public.scenarios(user_id,name,description,status)values($1,'Salary experiment','Fixture','active')returning id",[USER_A])).rows[0]!.id;await db.query("insert into public.scenario_changes(user_id,scenario_id,change_type,destination_account_id,effective_on,amount_minor,label,sort_order)values($1,$2,'add_one_off_income',$3,'2026-10-01',500000,'Fixture bonus',1)",[USER_A,planA,accountA]);});
afterAll(async()=>db.close());
describe.sequential("Phase 7 Plans database",()=>{
 it("upgrades scenarios and protects change targets by owner",async()=>{const columns=await db.query<{column_name:string}>("select column_name from information_schema.columns where table_schema='public' and table_name='scenarios' and column_name in('status','start_on','end_on','comparison_enabled','applied_at')");expect(columns.rows).toHaveLength(5);await expect(asUser(USER_A,()=>db.query("insert into public.scenario_changes(user_id,scenario_id,change_type,target_recurring_rule_id,amount_minor)values($1,$2,'modify_recurring_rule',$3,4000000)",[USER_A,planA,ruleB]))).rejects.toThrow();});
 it("requires a fresh explicit preview token",async()=>{const preview=await asUser(USER_A,()=>db.query<{value:any}>("select public.preview_plan_application($1)value",[planA]));const token=preview.rows[0]!.value.confirmation_token;expect(preview.rows[0]!.value).toMatchObject({requires_confirmation:true,change_count:1,actual_transactions_created:0});await db.query("update public.scenario_changes set label='Updated fixture bonus' where scenario_id=$1",[planA]);await expect(asUser(USER_A,()=>db.query("select public.apply_plan_to_base($1,$2)",[planA,token]))).rejects.toThrow(/stale/i);expect((await db.query<{count:number}>("select count(*)::int count from public.forecast_items where applied_scenario_change_id is not null")).rows[0]!.count).toBe(0);});
 it("applies assumptions atomically and idempotently without actual ledger activity",async()=>{const before=(await db.query<{count:number}>("select count(*)::int count from public.transactions where user_id=$1",[USER_A])).rows[0]!.count;const preview=(await asUser(USER_A,()=>db.query<{value:any}>("select public.preview_plan_application($1)value",[planA]))).rows[0]!.value;const first=(await asUser(USER_A,()=>db.query<{value:any}>("select public.apply_plan_to_base($1,$2)value",[planA,preview.confirmation_token]))).rows[0]!.value;const second=(await asUser(USER_A,()=>db.query<{value:any}>("select public.apply_plan_to_base($1,$2)value",[planA,preview.confirmation_token]))).rows[0]!.value;expect(first.actual_transactions_created).toBe(0);expect(second.already_applied).toBe(true);expect((await db.query<{count:number}>("select count(*)::int count from public.forecast_items where applied_scenario_change_id is not null")).rows[0]!.count).toBe(1);expect((await db.query<{count:number}>("select count(*)::int count from public.transactions where user_id=$1",[USER_A])).rows[0]!.count).toBe(before);expect((await db.query<{status:string}>("select status from public.scenarios where id=$1",[planA])).rows[0]!.status).toBe("applied");});
 it("rolls back every change when one assumption cannot map cleanly",async()=>{const failed=(await db.query<{id:string}>("insert into public.scenarios(user_id,name,status)values($1,'Atomic failure','active')returning id",[USER_A])).rows[0]!.id;await db.query("insert into public.scenario_changes(user_id,scenario_id,change_type,destination_account_id,effective_on,amount_minor,label,sort_order)values($1,$2,'add_one_off_income',$3,'2026-11-01',100000,'Would roll back',1)",[USER_A,failed,accountA]);await db.query("insert into public.scenario_changes(user_id,scenario_id,change_type,target_recurring_rule_id,effective_on,amount_minor,label,sort_order)values($1,$2,'modify_recurring_rule',$3,'2027-01-01',4000000,'Dated rule',2)",[USER_A,failed,ruleA]);const preview=(await asUser(USER_A,()=>db.query<{value:any}>("select public.preview_plan_application($1)value",[failed]))).rows[0]!.value;await expect(asUser(USER_A,()=>db.query("select public.apply_plan_to_base($1,$2)",[failed,preview.confirmation_token]))).rejects.toThrow(/review/i);expect((await db.query<{count:number}>("select count(*)::int count from public.forecast_items f join public.scenario_changes c on c.id=f.applied_scenario_change_id where c.scenario_id=$1",[failed])).rows[0]!.count).toBe(0);expect((await db.query<{status:string}>("select status from public.scenarios where id=$1",[failed])).rows[0]!.status).toBe("active");});
 it("prevents the second user from previewing or applying another user's Plan",async()=>{await expect(asUser(USER_B,()=>db.query("select public.preview_plan_application($1)",[planA]))).rejects.toThrow(/not found/i);await expect(asUser(USER_B,()=>db.query("select public.apply_plan_to_base($1,'bad')",[planA]))).rejects.toThrow();});
});
