import { toForecastInput, type BudgetWorkspace } from "./forecast";
import { comparePlans, evaluatePlans, type PlanInput, type ScenarioBaseInput, type ScenarioChange } from "~/domain/scenarios";
import type { PlanRow, ScenarioChangeRow } from "~/data/repositories/plans-repository";

export function toDomainChange(row:ScenarioChangeRow):ScenarioChange{return{id:row.id,scenarioId:row.scenario_id,changeType:row.change_type as ScenarioChange["changeType"],targetForecastItemId:row.target_forecast_item_id,targetRecurringRuleId:row.target_recurring_rule_id,targetAllocationItemId:row.target_allocation_item_id,targetGoalId:row.target_goal_id,sourceAccountId:row.source_account_id,destinationAccountId:row.destination_account_id,categoryId:row.category_id,fundId:row.fund_id,effectiveOn:row.effective_on,effectiveUntil:row.effective_until,amountMinor:row.amount_minor==null?null:Number(row.amount_minor),label:row.label,confidence:row.confidence,targetField:row.target_field as ScenarioChange["targetField"],booleanValue:row.boolean_value,frequency:row.frequency,intervalCount:row.interval_count,dayOfMonth:row.day_of_month,dayOfWeek:row.day_of_week,payload:row.payload_json&&typeof row.payload_json==="object"&&!Array.isArray(row.payload_json)?row.payload_json:{},sortOrder:row.sort_order};}
export function toPlans(rows:PlanRow[],changes:ScenarioChangeRow[]):PlanInput[]{return rows.map(plan=>({id:plan.id,name:plan.name,description:plan.description,status:plan.status,changes:changes.filter(change=>change.scenario_id===plan.id).map(toDomainChange)}));}
export function toScenarioBase(workspace:{forecast:any;funds:any;budgets:BudgetWorkspace},asOfDate?:string,horizonMonths?:number):ScenarioBaseInput{const forecast=toForecastInput(workspace.forecast,horizonMonths??Number(workspace.forecast.profile.forecast_horizon_months??12),[],asOfDate,workspace.budgets);return{forecast,safetyWindowDays:Number(workspace.funds.profile.safety_window_days??30),allocationItems:workspace.funds.items.map((row:any)=>({id:row.id,label:row.label,mode:row.mode,priority:row.priority,amountMinor:Number(row.amount_minor),active:row.active,destinationType:row.destination_type,destinationFundId:row.destination_fund_id,destinationAccountId:row.destination_account_id,stopBasis:row.stop_basis,startsOn:row.starts_on,endsOn:row.ends_on,activationSourceItemId:row.activation_source_item_id})),goals:workspace.funds.goals.map((row:any)=>({id:row.id,name:row.name,fundId:row.fund_id,targetMinor:row.target_minor==null?null:Number(row.target_minor),preferredMinor:row.preferred_balance_minor==null?null:Number(row.preferred_balance_minor),capMinor:row.cap_minor==null?null:Number(row.cap_minor),preferredContributionMinor:row.preferred_contribution_minor==null?null:Number(row.preferred_contribution_minor)}))};}
export function buildSelectedPlansEvaluation(workspace:{forecast:any;funds:any;budgets:BudgetWorkspace;plans:PlanRow[];changes:ScenarioChangeRow[]},selectedIds:string[],asOfDate?:string,horizonMonths?:number){const selected=toPlans(workspace.plans,workspace.changes).filter(plan=>selectedIds.includes(plan.id)),legacySelectedIds=selected.filter(plan=>plan.changes.length===0).map(plan=>plan.id),base=toScenarioBase(workspace,asOfDate,horizonMonths);base.forecast.selectedScenarioIds=legacySelectedIds;return evaluatePlans(base,selected);}
export function buildPlansComparison(workspace:{forecast:any;funds:any;budgets:BudgetWorkspace;plans:PlanRow[];changes:ScenarioChangeRow[]},selectedIds:string[],asOfDate?:string){const plans=toPlans(workspace.plans,workspace.changes),selected=plans.filter(plan=>selectedIds.includes(plan.id));return comparePlans(toScenarioBase(workspace,asOfDate),selected.map(plan=>({label:plan.name,plans:[plan]})).concat(selected.length>1?[{label:selected.map(plan=>plan.name).join(" + "),plans:selected}]:[]));}
