export type AnalyticsAccountClass="asset"|"liability"|"income"|"expense"|"equity";
export interface AnalyticsAccount{id:string;name:string;class:AnalyticsAccountClass;subtype:string;liquidityClass:string;includeInNetWorth:boolean;isSystem:boolean}
export interface AnalyticsEntry{accountId:string;amountMinor:number;categoryId:string|null}
export interface AnalyticsTransaction{id:string;kind:string;status:"draft"|"posted"|"void";occurredAt:string;description:string;reversesTransactionId:string|null;entries:AnalyticsEntry[]}
export interface MonthlyCashFlow{month:string;incomeMinor:number;expenseMinor:number;netMinor:number}
export interface CategorySpend{categoryId:string|null;label:string;amountMinor:number;share:number;previousMinor:number|null;changeMinor:number|null}
export interface NetWorthPoint{date:string;netWorthMinor:number;cashMinor:number;authoritative:true}

function dateInZone(value:string,timeZone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(value));const get=(type:string)=>parts.find(part=>part.type===type)?.value??"";return `${get("year")}-${get("month")}-${get("day")}`;}
function posted(rows:readonly AnalyticsTransaction[]){return rows.filter(row=>row.status==="posted").toSorted((a,b)=>a.occurredAt.localeCompare(b.occurredAt)||a.id.localeCompare(b.id));}
function accountMap(accounts:readonly AnalyticsAccount[]){return new Map(accounts.map(row=>[row.id,row]));}

/** External cash flow comes from income/expense ledger accounts. Transfers, opening state and Fund movements never enter it. */
export function aggregateMonthlyCashFlow(transactions:readonly AnalyticsTransaction[],accounts:readonly AnalyticsAccount[],timeZone:string):MonthlyCashFlow[]{const byAccount=accountMap(accounts),months=new Map<string,{income:number;expense:number}>();for(const transaction of posted(transactions)){const month=dateInZone(transaction.occurredAt,timeZone).slice(0,7);const value=months.get(month)??{income:0,expense:0};for(const entry of transaction.entries){const account=byAccount.get(entry.accountId);if(account?.class==="income")value.income-=entry.amountMinor;if(account?.class==="expense")value.expense+=entry.amountMinor;}months.set(month,value);}return [...months].map(([month,value])=>({month,incomeMinor:value.income,expenseMinor:value.expense,netMinor:value.income-value.expense})).toSorted((a,b)=>a.month.localeCompare(b.month));}

export function aggregateCategorySpend(transactions:readonly AnalyticsTransaction[],accounts:readonly AnalyticsAccount[],categories:ReadonlyMap<string,string>,timeZone:string,month:string):CategorySpend[]{const byAccount=accountMap(accounts),previousDate=new Date(`${month}-01T00:00:00Z`);previousDate.setUTCMonth(previousDate.getUTCMonth()-1);const previous=previousDate.toISOString().slice(0,7),totals=new Map<string|null,{current:number;previous:number}>();for(const transaction of posted(transactions)){const rowMonth=dateInZone(transaction.occurredAt,timeZone).slice(0,7);if(rowMonth!==month&&rowMonth!==previous)continue;for(const entry of transaction.entries){if(byAccount.get(entry.accountId)?.class!=="expense")continue;const value=totals.get(entry.categoryId)??{current:0,previous:0};if(rowMonth===month)value.current+=entry.amountMinor;else value.previous+=entry.amountMinor;totals.set(entry.categoryId,value);}}const total=[...totals.values()].reduce((sum,row)=>sum+Math.max(0,row.current),0);return [...totals].filter(([,row])=>row.current!==0).map(([categoryId,row])=>({categoryId,label:categoryId?categories.get(categoryId)??"Unclassified":"Unclassified",amountMinor:row.current,share:total>0?Math.max(0,row.current)/total:0,previousMinor:row.previous,changeMinor:row.current-row.previous})).toSorted((a,b)=>b.amountMinor-a.amountMinor||a.label.localeCompare(b.label));}

/** Ledger-derived history begins at the first posted transaction; nothing is fabricated before cutover. */
export function deriveNetWorthSeries(transactions:readonly AnalyticsTransaction[],accounts:readonly AnalyticsAccount[],timeZone:string):NetWorthPoint[]{const byAccount=accountMap(accounts),daily=new Map<string,{net:number;cash:number}>();let net=0,cash=0;for(const transaction of posted(transactions)){for(const entry of transaction.entries){const account=byAccount.get(entry.accountId);if(!account||account.isSystem)continue;if(account.includeInNetWorth&&(account.class==="asset"||account.class==="liability"))net+=entry.amountMinor;if(account.class==="asset"&&(account.liquidityClass==="operating"||account.liquidityClass==="liquid"))cash+=entry.amountMinor;}daily.set(dateInZone(transaction.occurredAt,timeZone),{net,cash});}return [...daily].map(([date,value])=>({date,netWorthMinor:value.net,cashMinor:value.cash,authoritative:true as const})).toSorted((a,b)=>a.date.localeCompare(b.date));}

export function currentFinancialPosition(accounts:readonly AnalyticsAccount[],balances:ReadonlyMap<string|null,number>,allocatedMinor:number){let totalCash=0,investments=0,assets=0,liabilities=0;for(const account of accounts){if(account.isSystem)continue;const balance=balances.get(account.id)??0;if(account.class==="asset"&&account.includeInNetWorth)assets+=balance;if(account.class==="liability"&&account.includeInNetWorth)liabilities+=balance;if(account.class==="asset"&&(account.liquidityClass==="operating"||account.liquidityClass==="liquid"))totalCash+=balance;if(account.class==="asset"&&account.liquidityClass==="invested")investments+=balance;}return{totalCashMinor:totalCash,allocatedCashMinor:allocatedMinor,unallocatedCashMinor:totalCash-allocatedMinor,investmentBookValueMinor:investments,totalAssetsMinor:assets,totalLiabilitiesMinor:liabilities,netWorthMinor:assets-liabilities};}
