import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { render,screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router";
import type { ReactNode } from "react";
import { describe,expect,it,vi } from "vitest";
import FundsRoute from "~/routes/funds";
import FundsPaydayRoute from "~/routes/funds-payday";

const fundWorkspace={funds:[{id:"fund",user_id:"user",backing_account_id:"cash",name:"Emergency",purpose_key:"emergency",currency:"NOK",color:null,icon:null,sort_order:1,active:true}],balances:[{fund_id:"fund",backing_account_id:"cash",balance_minor:0,currency:"NOK"}],goals:[{id:"goal",fund_id:"fund",name:"Emergency goal",target_minor:4_500_000,preferred_balance_minor:null,cap_minor:null,preferred_contribution_minor:500_000,floor_minor:null,target_date:null,status:"active",is_primary:true}],movements:[],plans:[{id:"plan",name:"Payday plan",trigger_kind:"payday",source_account_id:"cash",active:true,is_default:true}],items:[{id:"item",plan_id:"plan",label:"Emergency",destination_type:"fund" as const,destination_fund_id:"fund",destination_account_id:null,amount_minor:500_000,mode:"recommended" as const,priority:1,stop_basis:"target" as const,activation_source_item_id:null,active:true,starts_on:null,ends_on:null}],backing:[{account_id:"cash",account_name:"Operating Cash",account_balance_minor:1_195_600,allocated_minor:0,unallocated_minor:1_195_600,backing_valid:true}],profile:{base_currency:"NOK",operating_floor_minor:900_000,safety_window_days:30},accounts:[{id:"cash",name:"Operating Cash",currency:"NOK",liquidity_class:"operating",subtype:"checking",is_system:false}]};
const forecastWorkspace={profile:{user_id:"user",base_currency:"NOK",timezone:"Europe/Oslo",operating_floor_minor:900_000,forecast_horizon_months:12,safety_window_days:30,schema_version:6,display_name:null,created_at:"",updated_at:""},accounts:[{id:"cash",user_id:"user",name:"Operating Cash",class:"asset" as const,subtype:"checking" as const,currency:"NOK",is_system:false,system_key:null,include_in_net_worth:true,liquidity_class:"operating" as const,valuation_mode:"ledger" as const,creation_idempotency_key:null,creation_payload:null,opened_on:null,archived_at:null,created_at:"",updated_at:""}],balances:[{user_id:"user",account_id:"cash",currency:"NOK",class:"asset" as const,ledger_balance_minor:1_195_600,display_balance_minor:1_195_600}],items:[],rules:[],occurrences:[],scenarios:[],categories:[],transactions:[],funds:[{id:"fund",name:"Emergency"}],fundBalances:[{fund_id:"fund",balance_minor:0}]};
vi.mock("~/data/repositories/funds-repository",()=>({fundsRepository:{getWorkspace:vi.fn(async()=>fundWorkspace),executePayday:vi.fn(),allocate:vi.fn(),release:vi.fn()}}));
vi.mock("~/data/repositories/forecast-repository",()=>({forecastRepository:{getWorkspace:vi.fn(async()=>forecastWorkspace)}}));
function show(element:ReactNode){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<MemoryRouter>{<QueryClientProvider client={client}>{element}</QueryClientProvider>}</MemoryRouter>);}
describe("Phase 6 UI",()=>{
 it("shows zero-balance funds and compact payday navigation",async()=>{show(<FundsRoute/>);expect(await screen.findByRole("heading",{name:"Emergency"})).toBeInTheDocument();expect(screen.queryByText(/starts at zero/i)).not.toBeInTheDocument();expect(screen.getByRole("link",{name:/review payday plan/i})).toHaveAttribute("href","/funds/payday");});
 it("lets the user choose payday amounts without recommendations",async()=>{show(<FundsPaydayRoute/>);expect(await screen.findByRole("heading",{name:"Set each amount"})).toBeInTheDocument();expect(screen.queryByText(/suggested|recommendation/i)).not.toBeInTheDocument();expect(screen.queryByText(/cash now/i)).not.toBeInTheDocument();const confirm=screen.getByRole("button",{name:/confirm fund allocations/i});expect(confirm).toBeDisabled();await userEvent.clear(screen.getByLabelText("Emergency amount"));await userEvent.type(screen.getByLabelText("Emergency amount"),"1000");expect(confirm).toBeEnabled();});
});
