import { describe,expect,it } from "vitest";
import { applyPlans,comparePlans,detectScenarioConflicts,evaluatePlans,type PlanInput,type ScenarioBaseInput,type ScenarioChange } from "~/domain/scenarios";

const base:ScenarioBaseInput={forecast:{asOfDate:"2026-09-01",endDate:"2027-02-28",timezone:"Europe/Oslo",baseCurrency:"NOK",operatingFloorMinor:10_000,accounts:[
 {id:"cash",name:"Operating",class:"asset",subtype:"checking",liquidityClass:"operating",balanceMinor:100_000,includeInNetWorth:true},
 {id:"invest",name:"Investment",class:"asset",subtype:"investment",liquidityClass:"invested",balanceMinor:20_000,includeInNetWorth:true}],
 forecastItems:[{id:"purchase",kind:"expense",date:"2026-10-15",amountMinor:5_000,sourceAccountId:"cash",label:"Base purchase",status:"expected"}],
 recurringRules:[{id:"salary",kind:"income",label:"Salary",destinationAccountId:"cash",amountMinor:30_000,frequency:"monthly",intervalCount:1,dayOfMonth:1,startOn:"2026-09-01",active:true},{id:"rent",kind:"expense",label:"Rent",sourceAccountId:"cash",amountMinor:10_000,frequency:"monthly",intervalCount:1,dayOfMonth:5,startOn:"2026-09-05",active:true}],recurrenceExceptions:[],selectedScenarioIds:[],funds:[{id:"travel",name:"Travel",balanceMinor:30_000}],projectedFundActions:[]},safetyWindowDays:30,
 allocationItems:[{id:"travel-contribution",label:"Travel",mode:"recommended",priority:1,amountMinor:4_000,active:true,destinationType:"fund",destinationFundId:"travel",stopBasis:"none"}],goals:[{id:"travel-goal",name:"Travel goal",fundId:"travel",targetMinor:40_000}]};
const change=(value:Partial<ScenarioChange>&Pick<ScenarioChange,"changeType">):ScenarioChange=>({...value,id:value.id??`c-${value.changeType}`,scenarioId:value.scenarioId??"p",payload:value.payload??{},sortOrder:value.sortOrder??0});
const plan=(id:string,changes:ScenarioChange[]):PlanInput=>({id,name:id,status:"active",changes:changes.map(row=>({...row,scenarioId:id}))});

describe("Phase 7 pure Plan engine",()=>{
 it("applies one-off income and expense with exact cash deltas",()=>{const income=comparePlans(base,[{label:"Bonus",plans:[plan("bonus",[change({changeType:"add_one_off_income",label:"Bonus",amountMinor:8_000,effectiveOn:"2026-10-01",destinationAccountId:"cash"})])]}]);expect(income.alternatives[0]!.deltas.endingOperatingCashMinor).toBe(8_000);const expense=comparePlans(base,[{label:"Trip",plans:[plan("trip",[change({changeType:"add_one_off_expense",label:"Trip",amountMinor:17_000,effectiveOn:"2026-10-01",sourceAccountId:"cash"})])]}]);expect(expense.alternatives[0]!.deltas.endingOperatingCashMinor).toBe(-17_000);expect(expense.alternatives[0]!.deltas.endingNetWorthMinor).toBe(-17_000);});
 it("keeps transfers net-worth neutral",()=>{const result=comparePlans(base,[{label:"Transfer",plans:[plan("transfer",[change({changeType:"add_one_off_transfer",label:"Invest",amountMinor:10_000,effectiveOn:"2026-10-01",sourceAccountId:"cash",destinationAccountId:"invest"})])]}]);expect(result.alternatives[0]!.deltas.endingNetWorthMinor).toBe(0);expect(result.alternatives[0]!.deltas.endingOperatingCashMinor).toBe(-10_000);});
 it("supports salary increases, decreases, temporary changes, and income ending",()=>{const higher=evaluatePlans(base,[plan("higher",[change({changeType:"modify_recurring_rule",targetRecurringRuleId:"salary",amountMinor:40_000,effectiveOn:"2026-10-01"})])]);expect(higher.result.totals.incomeMinor).toBeGreaterThan(evaluatePlans(base,[]).result.totals.incomeMinor);const lower=evaluatePlans(base,[plan("lower",[change({changeType:"modify_recurring_rule",targetRecurringRuleId:"salary",amountMinor:20_000,effectiveOn:"2026-10-01",effectiveUntil:"2026-11-30"})])]);expect(lower.result.totals.incomeMinor).toBeLessThan(evaluatePlans(base,[]).result.totals.incomeMinor);const ended=evaluatePlans(base,[plan("end",[change({changeType:"pause_recurring_rule",targetRecurringRuleId:"salary",effectiveOn:"2026-11-01"})])]);expect(ended.result.totals.incomeMinor).toBe(60_000);});
 it("temporarily changes rent then resumes the Base amount",()=>{const result=evaluatePlans(base,[plan("rent",[change({changeType:"modify_recurring_rule",targetRecurringRuleId:"rent",amountMinor:15_000,effectiveOn:"2026-10-01",effectiveUntil:"2026-11-30"})])]);expect(result.result.totals.expenseMinor-evaluatePlans(base,[]).result.totals.expenseMinor).toBe(10_000);});
 it("reduces cash and a linked Fund once for Fund-funded spending",()=>{const result=comparePlans(base,[{label:"Fund trip",plans:[plan("trip",[change({changeType:"add_one_off_expense",label:"Trip",amountMinor:17_000,effectiveOn:"2026-10-01",sourceAccountId:"cash",fundId:"travel"})])]}]);const alternative=result.alternatives[0]!;expect(alternative.deltas.endingNetWorthMinor).toBe(-17_000);expect((alternative.evaluation.result.fundSeries.at(-1)!.balancesMinor.travel??0)-(result.base.result.fundSeries.at(-1)!.balancesMinor.travel??0)).toBe(-17_000);});
 it("reuses allocation semantics for contribution changes and pauses",()=>{const increased=evaluatePlans(base,[plan("save",[change({changeType:"modify_fund_contribution",targetAllocationItemId:"travel-contribution",amountMinor:8_000})])]);expect(increased.result.fundSeries.at(-1)!.balancesMinor.travel??0).toBeGreaterThan(evaluatePlans(base,[]).result.fundSeries.at(-1)!.balancesMinor.travel??0);const paused=evaluatePlans(base,[plan("pause",[change({changeType:"pause_fund_contribution",targetAllocationItemId:"travel-contribution"})])]);expect(paused.allocationRecommendations[0]!.recommendedMinor).toBe(0);});
 it("changes goals, floor, and safety window only in derived input",()=>{const applied=applyPlans(base,[plan("settings",[change({changeType:"modify_goal",targetGoalId:"travel-goal",targetField:"target",amountMinor:50_000}),change({id:"floor",changeType:"modify_operating_floor",amountMinor:50_000}),change({id:"window",changeType:"modify_safety_window",amountMinor:60})])]);expect(applied.goals[0]!.targetMinor).toBe(50_000);expect(applied.forecast.operatingFloorMinor).toBe(50_000);expect(applied.safetyWindowDays).toBe(60);expect(base.goals[0]!.targetMinor).toBe(40_000);expect(base.forecast.operatingFloorMinor).toBe(10_000);});
 it("never mutates Base after repeated calculations",()=>{const snapshot=structuredClone(base);const p=plan("repeat",[change({changeType:"modify_recurring_rule",targetRecurringRuleId:"rent",amountMinor:20_000,effectiveOn:"2026-10-01"})]);evaluatePlans(base,[p]);evaluatePlans(base,[p]);expect(base).toEqual(snapshot);});
 it("combines separate targets deterministically regardless of Plan order",()=>{const a=plan("a",[change({changeType:"modify_recurring_rule",targetRecurringRuleId:"salary",amountMinor:40_000,effectiveOn:"2026-10-01"})]),b=plan("b",[change({changeType:"add_one_off_expense",label:"Trip",amountMinor:5_000,effectiveOn:"2026-11-01",sourceAccountId:"cash"})]);expect(evaluatePlans(base,[a,b]).result.endingNetWorthMinor).toBe(evaluatePlans(base,[b,a]).result.endingNetWorthMinor);});
 it("surfaces same-rule overlapping conflicts and omits both changes",()=>{const a=plan("a",[change({id:"a1",changeType:"modify_recurring_rule",targetRecurringRuleId:"salary",amountMinor:40_000,effectiveOn:"2027-01-01"})]),b=plan("b",[change({id:"b1",changeType:"modify_recurring_rule",targetRecurringRuleId:"salary",amountMinor:45_000,effectiveOn:"2027-01-01"})]);const result=evaluatePlans(base,[a,b]);expect(result.applied.conflicts).toHaveLength(1);expect(result.result.endingNetWorthMinor).toBe(evaluatePlans(base,[]).result.endingNetWorthMinor);});
 it("does not conflict for non-overlapping periods or separate targets",()=>{const a=plan("a",[change({id:"a1",changeType:"modify_recurring_rule",targetRecurringRuleId:"salary",amountMinor:40_000,effectiveOn:"2026-09-01",effectiveUntil:"2026-10-31"})]),b=plan("b",[change({id:"b1",changeType:"modify_recurring_rule",targetRecurringRuleId:"salary",amountMinor:45_000,effectiveOn:"2026-11-01",effectiveUntil:"2027-01-31"})]),c=plan("c",[change({id:"c1",changeType:"modify_goal",targetGoalId:"travel-goal",targetField:"target",amountMinor:50_000})]);expect(detectScenarioConflicts([a,b,c])).toHaveLength(0);});
 it("detects suppress-versus-modify and overlapping Goal conflicts",()=>{const a=plan("a",[change({id:"a1",changeType:"suppress_forecast_item",targetForecastItemId:"purchase"}),change({id:"a2",changeType:"modify_goal",targetGoalId:"travel-goal",targetField:"target",amountMinor:50_000})]),b=plan("b",[change({id:"b1",changeType:"modify_forecast_item",targetForecastItemId:"purchase",amountMinor:8_000}),change({id:"b2",changeType:"modify_goal",targetGoalId:"travel-goal",targetField:"target",amountMinor:60_000})]);expect(detectScenarioConflicts([a,b])).toHaveLength(2);});
 it("leaves overdue and horizon behavior to the canonical engine",()=>{const overdueBase=structuredClone(base);overdueBase.forecast.forecastItems=[...overdueBase.forecast.forecastItems,{id:"old",kind:"expense",date:"2026-08-01",amountMinor:100,sourceAccountId:"cash",label:"Old",status:"expected"}];expect(evaluatePlans(overdueBase,[]).result.overdueItems).toHaveLength(1);expect(evaluatePlans(overdueBase,[]).result.endDate).toBe("2027-02-28");});
 it("changes safe-to-spend without changing actual cash when floor increases",()=>{const result=comparePlans(base,[{label:"Floor",plans:[plan("floor",[change({changeType:"modify_operating_floor",amountMinor:50_000})])]}]);expect(result.alternatives[0]!.deltas.safeToSpendMinor).toBeLessThan(0);expect(result.alternatives[0]!.evaluation.result.dailySeries[0]!.operatingCashMinor).toBe(result.base.result.dailySeries[0]!.operatingCashMinor);});
});
