import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { cleanup,render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter } from "react-router";
import type { ReactNode } from "react";
import { afterEach,describe,expect,it,vi } from "vitest";
import FundsRoute from "~/routes/funds";
import FundsPaydayRoute from "~/routes/funds-payday";
import { fundsRepository } from "~/data/repositories/funds-repository";

const fundWorkspace={funds:[{id:"fund",user_id:"user",backing_account_id:"cash",name:"Emergency",purpose_key:"emergency",currency:"NOK",color:null,icon:null,sort_order:1,active:true}],balances:[{fund_id:"fund",backing_account_id:"cash",balance_minor:0,currency:"NOK"}],goals:[{id:"goal",fund_id:"fund",name:"Emergency goal",target_minor:4_500_000,preferred_balance_minor:null,cap_minor:null,preferred_contribution_minor:500_000,floor_minor:null,target_date:null,status:"active",is_primary:true}],movements:[],plans:[{id:"plan",name:"Payday plan",trigger_kind:"payday",source_account_id:"cash",active:true,is_default:true}],items:[{id:"item",plan_id:"plan",label:"Emergency",destination_type:"fund" as const,destination_fund_id:"fund",destination_account_id:null,amount_minor:500_000,mode:"recommended" as const,priority:1,stop_basis:"target" as const,activation_source_item_id:null,active:true,starts_on:null,ends_on:null}],backing:[{account_id:"cash",account_name:"Operating Cash",account_balance_minor:1_195_600,allocated_minor:0,unallocated_minor:1_195_600,backing_valid:true}],profile:{base_currency:"NOK",operating_floor_minor:900_000,safety_window_days:30},accounts:[{id:"cash",name:"Operating Cash",currency:"NOK",liquidity_class:"operating",subtype:"checking",is_system:false}]};
const forecastWorkspace={profile:{user_id:"user",base_currency:"NOK",timezone:"Europe/Oslo",operating_floor_minor:900_000,forecast_horizon_months:12,safety_window_days:30,schema_version:6,display_name:null,created_at:"",updated_at:""},accounts:[{id:"cash",user_id:"user",name:"Operating Cash",class:"asset" as const,subtype:"checking" as const,currency:"NOK",is_system:false,system_key:null,include_in_net_worth:true,liquidity_class:"operating" as const,valuation_mode:"ledger" as const,creation_idempotency_key:null,creation_payload:null,opened_on:null,archived_at:null,created_at:"",updated_at:""}],balances:[{user_id:"user",account_id:"cash",currency:"NOK",class:"asset" as const,ledger_balance_minor:1_195_600,display_balance_minor:1_195_600}],items:[],rules:[],occurrences:[],scenarios:[],categories:[],transactions:[],funds:[{id:"fund",name:"Emergency"}],fundBalances:[{fund_id:"fund",balance_minor:0}]};
vi.mock("~/data/repositories/funds-repository",()=>({fundsRepository:{getWorkspace:vi.fn(async()=>fundWorkspace),updatePlanItem:vi.fn(),executePayday:vi.fn(),allocate:vi.fn(),release:vi.fn()}}));
vi.mock("~/data/repositories/forecast-repository",()=>({forecastRepository:{getWorkspace:vi.fn(async()=>forecastWorkspace)}}));
vi.mock("~/data/repositories/budgets-repository",()=>({budgetsRepository:{getWorkspace:vi.fn(async()=>({periods:[],lines:[],groups:[],groupCategories:[],actuals:[],commitments:[],categories:[],currency:"NOK"}))}}));
function show(element:ReactNode){const client=new QueryClient({defaultOptions:{queries:{retry:false}}});return render(<MemoryRouter>{<QueryClientProvider client={client}>{element}</QueryClientProvider>}</MemoryRouter>);}
afterEach(()=>cleanup());
describe("Phase 6 UI",()=>{
 it("shows zero-balance funds and compact payday navigation",async()=>{show(<FundsRoute/>);expect(await screen.findByRole("heading",{name:"Emergency"})).toBeInTheDocument();expect(screen.queryByText(/starts at zero/i)).not.toBeInTheDocument();expect(screen.getByRole("link",{name:/review payday plan/i})).toHaveAttribute("href","/funds/payday");});
 it("loads and saves payday amounts without recommendation, availability, or completion clutter",async()=>{show(<FundsPaydayRoute/>);expect(await screen.findByRole("heading",{name:"Set each amount"})).toBeInTheDocument();expect(screen.queryByText(/suggested|recommendation/i)).not.toBeInTheDocument();expect(screen.queryByText(/cash now|available today|remaining|complete|capped/i)).not.toBeInTheDocument();const input=screen.getByLabelText("Emergency amount");expect(input).toHaveValue(5000);await userEvent.clear(input);await userEvent.type(input,"1000");const confirm=screen.getByRole("button",{name:/confirm fund allocations/i});expect(confirm).toBeEnabled();await userEvent.click(confirm);await waitFor(()=>expect(fundsRepository.updatePlanItem).toHaveBeenCalledWith("item",{amount_minor:100_000}));expect(fundsRepository.executePayday).toHaveBeenCalled();});
 it("explains the allocation guardrail in plain language",async()=>{show(<FundsPaydayRoute/>);const input=await screen.findByLabelText("Emergency amount");await userEvent.clear(input);await userEvent.type(input,"999999");expect(screen.getByText(/money already in funds, upcoming bills, and your .* cash minimum are covered/i)).toBeVisible();expect(screen.getByText(/change the cash minimum in Settings/i)).toBeVisible();expect(screen.queryByText(/safe allocation limit/i)).not.toBeInTheDocument();});
});
