import {cleanup,render,screen} from "@testing-library/react";
import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {MemoryRouter} from "react-router";
import {beforeEach,describe,expect,it,vi} from "vitest";
import OverviewRoute from "~/routes/overview";
import AnalyticsRoute from "~/routes/analytics";
const overview={currency:"NOK",safeToSpendMinor:295600,operatingFloorMinor:900000,safetyWindowDays:30,nextReliableIncome:null,position:{totalCashMinor:1195600,allocatedCashMinor:0,unallocatedCashMinor:1195600,netWorthMinor:1195600,investmentBookValueMinor:0},projection:{date:"2026-09-19",liquidCashMinor:1395600,minDate:"2026-08-19",maxDate:"2027-08-19"},forecast:{endDate:"2027-08-19",endingOperatingCashMinor:2000000,lowest:{date:"2026-09-01",balanceMinor:1000000},firstBreach:null,incomeMinor:0,expenseMinor:0,chart:[]},funds:[{id:"f",name:"Emergency",balanceMinor:0,targetMinor:4500000,progress:0,projectedBalanceMinor:0,projectedCompletion:null,contributionMode:"recommended",nextContributionMinor:500000}],currentFlow:{month:"2026-08",incomeMinor:0,expenseMinor:0,netMinor:0},currentBudget:null,upcoming:[],overdue:[],recent:[],selectedPlanIds:[],planAlternative:null};
const analytics={currency:"NOK",timeZone:"Europe/Oslo",currentMonth:"2026-08",cashFlow:[],spending:[],netWorth:[{date:"2026-08-19",netWorthMinor:1195600,cashMinor:1195600,authoritative:true}],budgetPeriods:[],cutoverDate:"2026-08-19"};
const {reconcileAccount}=vi.hoisted(()=>({reconcileAccount:vi.fn()}));
vi.mock("~/data/repositories/analytics-repository",()=>({analyticsRepository:{getWorkspace:vi.fn(async()=>({forecast:{accounts:[{id:"cash",is_system:false,class:"asset",liquidity_class:"operating"}],balances:[{account_id:"cash",display_balance_minor:1195600}]}}))}}));
vi.mock("~/data/repositories/snapshots-repository",()=>({snapshotsRepository:{reconcileAccount}}));
vi.mock("~/read-models/overview",()=>({buildOverviewReadModel:vi.fn(()=>overview),buildAnalyticsReadModel:vi.fn(()=>analytics)}));
function show(node:React.ReactNode){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter>{node}</MemoryRouter></QueryClientProvider>)}
describe("Phase 8 cockpit UI",()=>{beforeEach(()=>{cleanup();vi.clearAllMocks()});
 it("renders the simplified current-position metrics",async()=>{show(<OverviewRoute/>);expect((await screen.findAllByText("Total current balance"))[0]).toBeVisible();expect(screen.getByText("Allocated to funds")).toBeVisible();expect(screen.getByText("Net worth")).toBeVisible();expect(screen.getByText("Projected balance")).toBeVisible();expect(screen.queryByText("Safe to spend")).not.toBeInTheDocument()});
 it("renders only the useful Fund, cash-flow and upcoming sections",async()=>{show(<OverviewRoute/>);expect(await screen.findByText("Emergency")).toBeVisible();expect(screen.getByText("Monthly cash flow")).toBeVisible();expect(screen.getByText("Upcoming")).toBeVisible();expect(screen.getByText(/Opening balances, transfers and fund allocations are excluded/)).toBeVisible();expect(screen.queryByText("Budgeted")).not.toBeInTheDocument()});
 it("opens the confirmed adjustment flow from total current balance",async()=>{show(<OverviewRoute/>);const edit=await screen.findByRole("button",{name:"Edit total current balance"});expect(edit).toBeEnabled();edit.click();expect(await screen.findByLabelText("New total current balance")).toHaveValue("11956.00");expect(screen.getByText(/traceable adjustment/)).toBeVisible()});
 it("renders a compact chart-led analytics dashboard without the retired net-worth card",async()=>{show(<AnalyticsRoute/>);expect(await screen.findByRole("combobox",{name:"Month"})).toHaveDisplayValue("August 2026");expect(screen.getByRole("heading",{name:"Monthly cash flow"})).toBeVisible();expect(screen.getByRole("heading",{name:"Spending by category"})).toBeVisible();expect(screen.getByRole("heading",{name:"Budget performance"})).toBeVisible();expect(screen.queryByRole("heading",{name:"Net worth since cutover"})).not.toBeInTheDocument();expect(screen.getByText(/Missing categories appear as Unclassified/)).toBeVisible()});
});
