import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { cleanup,render,screen,within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { createMemoryRouter,RouterProvider } from "react-router";
import { afterEach,describe,expect,it,vi } from "vitest";
import PlansRoute from "~/routes/plans";
import PlanDetailRoute from "~/routes/plan-detail";
import PlansCompareRoute from "~/routes/plans-compare";
const calls=vi.hoisted(()=>({create:vi.fn(),updatePlan:vi.fn(),duplicate:vi.fn(),add:vi.fn(),updateChange:vi.fn(),remove:vi.fn(),preview:vi.fn(async()=>({scenario_id:"trip",name:"Trip",confirmation_token:"preview-token",change_count:1,changes:[{id:"trip-cost",type:"add_one_off_expense",label:"Trip cost",amount_minor:1700000}],requires_confirmation:true as const,actual_transactions_created:0 as const})),apply:vi.fn()}));
const now="2026-09-01T00:00:00Z";
const plans=[{id:"salary-a",user_id:"user",name:"Salary A",description:"40k salary",status:"active" as const,start_on:null,end_on:null,comparison_enabled:true,legacy_source_id:null,migration_metadata:{},archived_at:null,applied_at:null,created_at:now,updated_at:now},{id:"salary-b",user_id:"user",name:"Salary B",description:"45k salary",status:"active" as const,start_on:null,end_on:null,comparison_enabled:true,legacy_source_id:null,migration_metadata:{},archived_at:null,applied_at:null,created_at:now,updated_at:now},{id:"trip",user_id:"user",name:"Trip",description:"Invented fixture trip",status:"draft" as const,start_on:null,end_on:null,comparison_enabled:false,legacy_source_id:"legacy-trip",migration_metadata:{},archived_at:null,applied_at:null,created_at:now,updated_at:now}];
const row=(id:string,scenario:string,amount:number)=>({id,user_id:"user",scenario_id:scenario,change_type:"modify_recurring_rule",target_forecast_item_id:null,target_recurring_rule_id:"salary",target_allocation_item_id:null,target_goal_id:null,source_account_id:null,destination_account_id:null,category_id:null,fund_id:null,effective_on:"2027-01-01",effective_until:null,amount_minor:amount,label:`${amount/100} salary`,confidence:"expected" as const,target_field:null,boolean_value:null,frequency:null,interval_count:null,day_of_month:null,day_of_week:null,payload_json:{},sort_order:0,created_at:now,updated_at:now});
const changes=[row("a-change","salary-a",4_000_000),row("b-change","salary-b",4_500_000),{...row("trip-cost","trip",1_700_000),change_type:"add_one_off_expense",target_recurring_rule_id:null,source_account_id:"cash",effective_on:"2026-10-01",label:"Trip cost"}];
const forecast={profile:{user_id:"user",base_currency:"NOK",timezone:"Europe/Oslo",operating_floor_minor:900000,forecast_horizon_months:12,safety_window_days:30,schema_version:7,display_name:null,created_at:now,updated_at:now},accounts:[{id:"cash",user_id:"user",name:"Operating Cash",class:"asset",subtype:"checking",currency:"NOK",is_system:false,system_key:null,include_in_net_worth:true,liquidity_class:"operating",valuation_mode:"ledger",creation_idempotency_key:null,creation_payload:null,opened_on:null,archived_at:null,created_at:now,updated_at:now}],balances:[{user_id:"user",account_id:"cash",currency:"NOK",class:"asset",ledger_balance_minor:1195600,display_balance_minor:1195600}],items:[],rules:[{id:"salary",user_id:"user",kind:"income",label:"Salary",notes:null,source_account_id:null,destination_account_id:"cash",category_id:null,amount_minor:3000000,frequency:"monthly",interval_count:1,day_of_month:1,day_of_week:null,start_on:"2026-09-01",end_on:null,default_sort_order:null,confidence:"expected",scenario_id:null,active:true,is_reliable_income:true,legacy_source_id:null,created_at:now,updated_at:now,archived_at:null}],occurrences:[],scenarios:plans,categories:[],transactions:[],funds:[{id:"travel",name:"Travel"}],fundBalances:[{fund_id:"travel",balance_minor:0}]};
const funds={funds:[{id:"travel",user_id:"user",backing_account_id:"cash",name:"Travel",purpose_key:"travel",currency:"NOK",color:null,icon:null,sort_order:1,active:true}],balances:[{fund_id:"travel",backing_account_id:"cash",balance_minor:0,currency:"NOK"}],goals:[{id:"goal",fund_id:"travel",name:"Travel goal",target_minor:4000000,preferred_balance_minor:null,cap_minor:null,preferred_contribution_minor:400000,floor_minor:null,target_date:null,status:"active",is_primary:true}],movements:[],plans:[],items:[{id:"contribution",plan_id:"payday",label:"Travel",destination_type:"fund",destination_fund_id:"travel",destination_account_id:null,amount_minor:400000,mode:"recommended",priority:1,stop_basis:"cap",activation_source_item_id:null,active:true,starts_on:null,ends_on:null}],backing:[],profile:{base_currency:"NOK",operating_floor_minor:900000,safety_window_days:30},accounts:[]};
const workspace={forecast,funds,plans,changes,applications:[]};
vi.mock("~/data/repositories/plans-repository",()=>({plansRepository:{getWorkspace:vi.fn(async()=>workspace),createPlan:calls.create,updatePlan:calls.updatePlan,duplicatePlan:calls.duplicate,addChange:calls.add,updateChange:calls.updateChange,removeChange:calls.remove,previewApply:calls.preview,applyToBase:calls.apply}}));
function show(path:string,element:React.ReactNode,pattern:string){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}),router=createMemoryRouter([{path:pattern,element}],{initialEntries:[path]});return render(<QueryClientProvider client={client}><RouterProvider router={router}/></QueryClientProvider>);}
afterEach(()=>cleanup());
describe("Phase 7 Plans UI",()=>{
 it("creates a Plan from a quick start without technical language",async()=>{show("/plans",<PlansRoute/>,"/plans");expect(await screen.findByRole("heading",{name:"Plans"})).toBeVisible();expect(await screen.findByText("Imported reference")).toBeVisible();await userEvent.click(screen.getByRole("button",{name:"Create plan"}));await userEvent.click(screen.getByRole("button",{name:"Large purchase"}));await userEvent.click(screen.getByRole("button",{name:"Save plan"}));expect(calls.create).toHaveBeenCalledWith(expect.objectContaining({name:"Large purchase"}));});
 it("adds and edits a compact assumption",async()=>{show("/plans/trip",<PlanDetailRoute/>,"/plans/:planId");expect(await screen.findByRole("heading",{name:"Trip"})).toBeVisible();const assumption=screen.getByText("Trip cost").closest("article")!;await userEvent.click(within(assumption).getByRole("button",{name:"Edit"}));const label=screen.getByLabelText("Label");await userEvent.clear(label);await userEvent.type(label,"Updated trip");await userEvent.click(screen.getByRole("button",{name:"Save assumption"}));expect(calls.updateChange).toHaveBeenCalledWith("trip-cost",expect.objectContaining({label:"Updated trip"}));});
 it("duplicates and archives a Plan",async()=>{show("/plans/salary-a",<PlanDetailRoute/>,"/plans/:planId");await screen.findByRole("heading",{name:"Salary A"});await userEvent.click(screen.getByRole("button",{name:"Duplicate Plan"}));await userEvent.click(screen.getByRole("button",{name:"Archive Plan"}));expect(calls.duplicate).toHaveBeenCalledWith("salary-a");expect(calls.updatePlan).toHaveBeenCalledWith("salary-a",expect.objectContaining({status:"archived"}));});
 it("compares Base, individual Plans, combined Plans, and surfaces conflicts",async()=>{show("/plans/compare",<PlansCompareRoute/>,"/plans/compare");expect(await screen.findByRole("heading",{name:"Base versus what-if"})).toBeVisible();expect(await screen.findByText("Salary A + Salary B")).toBeVisible();expect(screen.getByRole("alert")).toHaveTextContent(/plan changes conflict/i);await userEvent.click(screen.getByRole("checkbox",{name:"Salary B"}));expect(screen.queryByRole("alert")).not.toBeInTheDocument();});
 it("requires Apply preview, supports cancel, then explicit confirmation",async()=>{show("/plans/salary-a",<PlanDetailRoute/>,"/plans/:planId");await screen.findByRole("heading",{name:"Salary A"});await userEvent.click(screen.getByRole("button",{name:"Preview Apply to Base"}));expect(await screen.findByText(/0 actual transactions/i)).toBeVisible();await userEvent.click(screen.getByRole("button",{name:"Cancel"}));expect(screen.queryByRole("button",{name:"Confirm Apply to Base"})).not.toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"Preview Apply to Base"}));await userEvent.click(await screen.findByRole("button",{name:"Confirm Apply to Base"}));expect(calls.apply).toHaveBeenCalledWith("salary-a","preview-token");});
});
