import { useEffect,useMemo,useState } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Page } from "~/components/page";
import { forecastRepository } from "~/data/repositories/forecast-repository";
import { fundsRepository } from "~/data/repositories/funds-repository";
import { calculateSafeToSpend,recommendAllocations } from "~/domain/allocations";
import { asMinorUnits,formatMinorUnits } from "~/domain/money";
import { buildForecastScreenModel,calendarDateInTimezone } from "~/read-models/forecast";
function money(value:number,currency:string){return formatMinorUnits(asMinorUnits(value),currency);}
export default function FundsPaydayRoute(){const qc=useQueryClient();const query=useQuery({queryKey:["payday-workspace"],queryFn:async()=>({funds:await fundsRepository.getWorkspace(),forecast:await forecastRepository.getWorkspace()})});const [approved,setApproved]=useState<Record<string,number>>({});const [notice,setNotice]=useState("");
 const view=useMemo(()=>{if(!query.data)return null;const {funds,forecast}=query.data;const today=calendarDateInTimezone(forecast.profile.timezone);const model=buildForecastScreenModel(forecast,1,[],today);const operatingIds=new Set(funds.accounts.filter(row=>row.liquidity_class==="operating").map(row=>row.id));const allocatedOperating=funds.backing.filter(row=>operatingIds.has(row.account_id)).reduce((sum,row)=>sum+Number(row.allocated_minor),0);const safe=calculateSafeToSpend({dailyOperatingCash:model.result.dailySeries.map(row=>({date:row.date,balanceMinor:row.operatingCashMinor})),allocatedOperatingMinor:allocatedOperating,operatingFloorMinor:Number(funds.profile.operating_floor_minor??0),safetyWindowDays:Number(funds.profile.safety_window_days??30)});const plan=funds.plans.find(row=>row.is_default&&row.active);const result=recommendAllocations({asOfDate:today,safeAllocatableMinor:safe,items:funds.items.filter(row=>row.plan_id===plan?.id).map(row=>({id:row.id,label:row.label,mode:row.mode,priority:row.priority,amountMinor:Number(row.amount_minor),active:row.active,destinationType:row.destination_type,destinationFundId:row.destination_fund_id,destinationAccountId:row.destination_account_id,stopBasis:row.stop_basis,startsOn:row.starts_on,endsOn:row.ends_on,activationSourceItemId:row.activation_source_item_id})),fundBalancesMinor:Object.fromEntries(funds.balances.map(row=>[row.fund_id,Number(row.balance_minor)])),goals:funds.goals.map(row=>({fundId:row.fund_id,targetMinor:row.target_minor,preferredMinor:row.preferred_balance_minor,capMinor:row.cap_minor}))});return{plan,result,safe,currency:funds.profile.base_currency,floor:Number(funds.profile.operating_floor_minor??0),window:Number(funds.profile.safety_window_days??30)}},[query.data]);
 useEffect(()=>{if(view)setApproved(Object.fromEntries(view.result.recommendations.map(row=>[row.itemId,row.recommendedMinor])));},[view]);
 const execute=useMutation({mutationFn:async()=>{if(!view?.plan)throw new Error("No active payday plan.");const items=view.result.recommendations.map(row=>({plan_item_id:row.itemId,recommended_minor:row.recommendedMinor,approved_minor:Math.max(0,approved[row.itemId]??0)}));return fundsRepository.executePayday(view.plan.id,null,items,`payday-ui:${view.plan.id}:${crypto.randomUUID()}`);},onSuccess:()=>{setNotice("Allocation confirmed. Fund movements were created; account-transfer destinations remain explicit follow-up actions.");void qc.invalidateQueries();},onError:value=>setNotice(value instanceof Error?value.message:"Allocation failed")});
 return <Page eyebrow="Payday planning" title="Review before allocating" description="Recommendations protect the operating floor across the safety window. Nothing moves until you confirm.">{query.isLoading?<p className="muted">Calculating the plan…</p>:null}{query.error?<p className="field-error">The payday plan could not be loaded.</p>:null}{view?<><section className="money-summary"><div className="metric-card"><p>Safe to allocate</p><strong>{money(view.safe,view.currency)}</strong></div><div className="metric-card"><p>Operating floor</p><strong>{money(view.floor,view.currency)}</strong></div><div className="metric-card"><p>Safety window</p><strong>{view.window} days</strong></div><div className="metric-card"><p>Recommended</p><strong>{money(view.result.recommendations.reduce((sum,row)=>sum+row.recommendedMinor,0),view.currency)}</strong></div></section><section className="money-panel"><div className="panel-heading"><div><p className="section-kicker">{view.plan?.name??"Payday plan"}</p><h2>Recommendation</h2></div></div><div className="payday-list">{view.result.recommendations.map(row=><article className="payday-row" key={row.itemId}><div><strong>{row.label}</strong><p>{row.explanation}</p><small>{row.reason} · priority {row.priority}{row.destinationType==="account"?" · real transfer required":""}</small></div><label>Approved<input type="number" min="0" step="100" value={approved[row.itemId]??0} onChange={event=>setApproved(current=>({...current,[row.itemId]:Number(event.target.value)}))}/><span>{money(approved[row.itemId]??0,view.currency)}</span></label></article>)}</div>{notice?<p className={notice.startsWith("Allocation confirmed")?"form-notice":"field-error"}>{notice}</p>:null}<button className="primary-button" disabled={execute.isPending||view.result.recommendations.every(row=>(approved[row.itemId]??0)===0)} onClick={()=>execute.mutate()}>Confirm fund allocations</button><p className="form-help">Recommended mode is review-first. Investment destinations are recorded as requiring a separate real account transfer, never fabricated as a virtual movement.</p></section></>:null}</Page>}
