import { useState,type FormEvent } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Link,useParams } from "react-router";
import { Page } from "~/components/page";
import { fundsRepository } from "~/data/repositories/funds-repository";
import { asMinorUnits,formatMinorUnits,parseDisplayAmountToMinor } from "~/domain/money";
function money(value:number,currency:string){return formatMinorUnits(asMinorUnits(value),currency);}
export default function FundDetailRoute(){const {fundId}=useParams();const qc=useQueryClient();const workspace=useQuery({queryKey:["funds-workspace"],queryFn:()=>fundsRepository.getWorkspace()});const [amount,setAmount]=useState("");const [description,setDescription]=useState("");const [error,setError]=useState("");
 const fund=workspace.data?.funds.find(row=>row.id===fundId);const balance=Number(workspace.data?.balances.find(row=>row.fund_id===fundId)?.balance_minor??0);const goal=workspace.data?.goals.find(row=>row.fund_id===fundId&&row.is_primary);
 const command=useMutation({mutationFn:async(kind:"allocate"|"release")=>{if(!fundId)throw new Error("Fund unavailable");const minor=Number(parseDisplayAmountToMinor(amount));if(minor<=0)throw new Error("Enter a positive amount.");const key=`fund-ui:${kind}:${fundId}:${crypto.randomUUID()}`;if(kind==="allocate")await fundsRepository.allocate(fundId,minor,description||"Manual allocation",key);else await fundsRepository.release(fundId,minor,description||"Manual release",key);},onSuccess:()=>{setAmount("");setDescription("");setError("");void qc.invalidateQueries({queryKey:["funds-workspace"]});},onError:(value)=>setError(value instanceof Error?value.message:"Command failed")});
 function submit(event:FormEvent,kind:"allocate"|"release"){event.preventDefault();command.mutate(kind);}
 if(workspace.isLoading)return <Page eyebrow="Fund" title="Loading…" description="Loading the fund workspace."/>;if(!fund)return <Page eyebrow="Fund" title="Fund not found" description="This fund is unavailable or no longer active."><Link to="/funds">Back to funds</Link></Page>;
 return <Page eyebrow="Fund detail" title={fund.name} description="Balance, goal, recent movements, and explicit money commands for this virtual envelope."><section className="money-summary"><div className="metric-card"><p>Fund balance</p><strong>{money(balance,fund.currency)}</strong></div><div className="metric-card"><p>Preferred contribution</p><strong>{money(Number(goal?.preferred_contribution_minor??0),fund.currency)}</strong></div><div className="metric-card"><p>Target / cap</p><strong>{money(Number(goal?.target_minor??goal?.cap_minor??0),fund.currency)}</strong></div></section><div className="money-layout"><section className="money-panel"><div className="panel-heading"><div><p className="section-kicker">History</p><h2>Movements</h2></div></div><ul className="compact-list">{workspace.data?.movements.filter(row=>row.fund_id===fund.id).map(row=><li key={row.id}><span><strong>{row.description}</strong><small>{row.kind} · {new Date(row.occurred_at).toLocaleDateString()}</small></span><strong className={row.amount_minor<0?"negative":"positive"}>{money(Number(row.amount_minor),fund.currency)}</strong></li>)}</ul></section><section className="money-panel"><p className="section-kicker">Explicit command</p><h2>Allocate or release</h2><form className="money-form" onSubmit={event=>submit(event,"allocate")}><label>Amount<input value={amount} inputMode="decimal" onChange={event=>setAmount(event.target.value)} required/></label><label>Description<input value={description} onChange={event=>setDescription(event.target.value)} placeholder="Optional note"/></label>{error?<p className="field-error">{error}</p>:null}<button className="primary-button" disabled={command.isPending}>Allocate to fund</button><button type="button" disabled={command.isPending||balance===0} onClick={()=>command.mutate("release")}>Release to unallocated cash</button></form><p className="form-help">Neither action is spending. A fund spend is posted once through the actual expense workflow.</p></section></div></Page>}
