import { useState,type FormEvent } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router";
import { Drawer } from "~/components/drawer";
import { Page } from "~/components/page";
import { plansRepository } from "~/data/repositories/plans-repository";

export default function PlansRoute(){const qc=useQueryClient(),workspace=useQuery({queryKey:["plans-workspace"],queryFn:()=>plansRepository.getWorkspace()});const[name,setName]=useState(""),[description,setDescription]=useState(""),[error,setError]=useState(""),[drawerOpen,setDrawerOpen]=useState(false);
 const create=useMutation({mutationFn:()=>plansRepository.createPlan({name,description,status:"draft"}),onSuccess:()=>{setName("");setDescription("");setError("");setDrawerOpen(false);void qc.invalidateQueries({queryKey:["plans-workspace"]});},onError:value=>setError(value instanceof Error?value.message:"Plan could not be created")});
 const toggle=useMutation({mutationFn:({id,enabled}:{id:string;enabled:boolean})=>plansRepository.updatePlan(id,{comparison_enabled:enabled}),onSuccess:()=>void qc.invalidateQueries({queryKey:["plans-workspace"]})});
 function submit(event:FormEvent){event.preventDefault();if(!name.trim()){setError("Give the Plan a name.");return;}create.mutate();}
 const active=workspace.data?.plans.filter(plan=>plan.status==="active"||plan.status==="draft")??[],archived=workspace.data?.plans.filter(plan=>plan.status==="archived"||plan.status==="applied")??[];
 return <Page eyebrow="What if?" title="Plans" description="Try a future decision—such as a trip or a move—and compare its effect without changing your real money.">
  <div className="panel-heading page-actions"><p className="muted">Your current plan stays unchanged until you explicitly apply a scenario.</p><div className="button-row"><Link className="secondary-button" to="/plans/compare">Compare plans</Link><button className="primary-button" type="button" onClick={()=>setDrawerOpen(true)}>Create plan</button></div></div>
  {workspace.isLoading?<p className="muted">Loading Plans…</p>:null}{workspace.error?<p className="field-error">Plans could not be loaded.</p>:null}
  <section className="money-panel"><div className="panel-heading"><div><p className="section-kicker">Active plans</p><h2>What you are exploring</h2></div></div><div className="plan-list">{active.map(plan=>{const count=workspace.data!.changes.filter(change=>change.scenario_id===plan.id).length;return <article className="plan-row" key={plan.id}><div><span className="plan-status">{plan.legacy_source_id?"Imported reference":plan.status}</span><h3>{plan.name}</h3><p>{plan.description||"No description yet."}</p><small>{count} assumption{count===1?"":"s"}</small></div><div className="plan-actions"><label><input type="checkbox" checked={plan.comparison_enabled} onChange={event=>toggle.mutate({id:plan.id,enabled:event.target.checked})}/> Compare</label><Link to={`/plans/${plan.id}`}>Edit →</Link></div></article>})}{!active.length?<div className="inline-empty"><strong>No active plans</strong><span>Create one when you want to test a meaningful decision.</span></div>:null}</div></section>
  <Drawer open={drawerOpen} onClose={()=>setDrawerOpen(false)} eyebrow="New scenario" title="Explore one decision"><form className="money-form" onSubmit={submit}><label>Name<input value={name} onChange={event=>setName(event.target.value)} placeholder="e.g. New apartment"/></label><label>Description <span className="optional">optional</span><textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="What are you trying to understand?"/></label>{error?<p className="field-error">{error}</p>:null}<button className="primary-button" disabled={create.isPending}>Save plan</button></form><div className="quick-starts" aria-label="Plan quick starts"><span>Quick ideas</span>{["Trip","Salary change","Rent change","Large purchase","Monthly contribution","One-off income"].map(item=><button type="button" key={item} onClick={()=>{setName(item);setDescription(`Explore a ${item.toLowerCase()} assumption.`);}}>{item}</button>)}</div></Drawer>
  {archived.length?<section className="money-panel"><p className="section-kicker">Reference</p><h2>Archived and applied</h2><ul className="compact-list">{archived.map(plan=><li key={plan.id}><span><strong>{plan.name}</strong><small>{plan.status}</small></span><Link to={`/plans/${plan.id}`}>View</Link></li>)}</ul></section>:null}
 </Page>}
