import { useEffect,useMemo,useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router";
import { CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { Page } from "~/components/page";
import { plansRepository } from "~/data/repositories/plans-repository";
import { buildPlansComparison } from "~/read-models/plans";
import { asMinorUnits,formatMinorAxis,formatMinorUnits } from "~/domain/money";
function money(value:number,currency:string){return formatMinorUnits(asMinorUnits(value),currency)}
export default function PlansCompareRoute(){const workspace=useQuery({queryKey:["plans-workspace"],queryFn:()=>plansRepository.getWorkspace()}),[selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{if(workspace.data&&!selected.length)setSelected(workspace.data.plans.filter(plan=>plan.comparison_enabled&&(plan.status==="active"||plan.status==="draft")).slice(0,2).map(plan=>plan.id));},[workspace.data,selected.length]);
 const comparison=useMemo(()=>workspace.data?buildPlansComparison(workspace.data,selected):null,[workspace.data,selected]),currency=workspace.data?.forecast.profile.base_currency??"NOK";
 const chart=useMemo(()=>{if(!comparison)return[];const alternatives=comparison.alternatives;return comparison.base.result.dailySeries.filter((_,index)=>index%7===0).map((point,index)=>{const row:Record<string,string|number>={date:point.date,Base:point.operatingCashMinor};for(const alternative of alternatives)row[alternative.label]=alternative.evaluation.result.dailySeries[index*7]?.operatingCashMinor??alternative.evaluation.result.endingOperatingCashMinor;return row;});},[comparison]);
 const colors=["#bb5f43","#3e7356","#6f5a92"];
 return <Page eyebrow="Plan comparison" title="Base versus what-if" description="Compare up to two Plans and their combined effect. Conflicting assumptions are surfaced and never resolved silently."><div className="panel-heading"><Link to="/plans">← Plans</Link><span className="muted">Select at most two Plans</span></div>{workspace.isLoading?<p className="muted">Calculating comparisons…</p>:null}
  <section className="money-panel"><div className="scenario-options">{workspace.data?.plans.filter(plan=>plan.status==="active"||plan.status==="draft").map(plan=><label key={plan.id}><input type="checkbox" checked={selected.includes(plan.id)} disabled={!selected.includes(plan.id)&&selected.length>=2} onChange={event=>setSelected(current=>event.target.checked?[...current,plan.id]:current.filter(id=>id!==plan.id))}/>{plan.name}</label>)}</div></section>
  {comparison?<><section className="chart-card"><div><p className="eyebrow">Operating cash</p><h2>Cash over time</h2></div><div className="forecast-chart" aria-label="Base and selected Plan operating cash chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="date" minTickGap={40}/><YAxis tickFormatter={value=>formatMinorAxis(Number(value))}/><Tooltip formatter={value=>money(Number(value),currency)}/><Legend/><Line type="monotone" dataKey="Base" stroke="#24352f" dot={false}/>{comparison.alternatives.map((alternative,index)=><Line key={alternative.label} type="monotone" dataKey={alternative.label} stroke={colors[index]??"#bb5f43"} dot={false}/>)}</LineChart></ResponsiveContainer></div></section>
  <section className="comparison-grid"><article className="comparison-card"><p className="section-kicker">Base Plan</p><h2>{money(comparison.base.result.endingOperatingCashMinor,currency)}</h2><span>Ending operating cash</span><dl><div><dt>Lowest cash</dt><dd>{money(comparison.base.result.lowestOperatingCash.balanceMinor,currency)}</dd></div><div><dt>Safe-to-spend</dt><dd>{money(comparison.base.safeToSpendMinor,currency)}</dd></div><div><dt>Floor breaches</dt><dd>{comparison.base.result.floorBreaches.length}</dd></div></dl></article>{comparison.alternatives.map(alternative=><article className="comparison-card" key={alternative.label}><p className="section-kicker">{alternative.label}</p><h2>{money(alternative.evaluation.result.endingOperatingCashMinor,currency)}</h2><span>Impact {money(alternative.deltas.endingOperatingCashMinor,currency)}</span><dl><div><dt>Lowest cash</dt><dd>{money(alternative.evaluation.result.lowestOperatingCash.balanceMinor,currency)} <small>{money(alternative.deltas.lowestOperatingCashMinor,currency)}</small></dd></div><div><dt>Net worth impact</dt><dd>{money(alternative.deltas.endingNetWorthMinor,currency)}</dd></div><div><dt>Safe-to-spend impact</dt><dd>{money(alternative.deltas.safeToSpendMinor,currency)}</dd></div><div><dt>Income impact</dt><dd>{money(alternative.deltas.incomeMinor,currency)}</dd></div><div><dt>Expense impact</dt><dd>{money(alternative.deltas.expenseMinor,currency)}</dd></div><div><dt>Floor breaches</dt><dd>{alternative.evaluation.result.floorBreaches.length}</dd></div></dl>{alternative.evaluation.applied.conflicts.length?<div className="conflict-box" role="alert"><strong>{alternative.evaluation.applied.conflicts.length} target conflict{alternative.evaluation.applied.conflicts.length===1?"":"s"}</strong>{alternative.evaluation.applied.conflicts.map(conflict=><p key={conflict.targetKey}>{conflict.message} · {conflict.targetKey}</p>)}<span>Deselect one conflicting Plan to resolve.</span></div>:null}<ul className="health-list">{alternative.evaluation.health.map(signal=><li data-kind={signal.kind} key={`${signal.label}:${signal.detail}`}><strong>{signal.label}</strong><span>{signal.detail}</span></li>)}</ul></article>)}</section></>:null}
 </Page>}
