import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Page } from "~/components/page";
import { forecastRepository } from "~/data/repositories/forecast-repository";
import { recurringRepository } from "~/data/repositories/recurring-repository";
import { asMinorUnits, formatMinorUnits, parseDisplayAmountToMinor } from "~/domain/money";

function describe(rule: { frequency: string; interval_count: number; day_of_month: number | null; day_of_week: number | null; end_on: string | null }): string {
  const cadence = rule.interval_count === 1 ? rule.frequency : `every ${rule.interval_count} ${rule.frequency.replace("ly", "")}s`;
  const day = rule.frequency === "weekly" ? ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"][rule.day_of_week ?? 0] : `day ${rule.day_of_month}`;
  return `Repeats ${cadence} · ${day}${rule.end_on ? ` · Ends ${rule.end_on}` : ""}`;
}

export default function RecurringSettingsRoute() {
  const queryClient = useQueryClient(); const workspace = useQuery({ queryKey: ["forecast-workspace"], queryFn: () => forecastRepository.getWorkspace() });
  const [editingId, setEditingId] = useState<string | null>(null); const [kind, setKind] = useState<"income" | "expense" | "transfer">("expense");
  const [label, setLabel] = useState(""); const [amount, setAmount] = useState(""); const [frequency, setFrequency] = useState<"weekly" | "monthly" | "yearly">("monthly");
  const [intervalCount, setIntervalCount] = useState(1); const [day, setDay] = useState(1); const [startOn, setStartOn] = useState(""); const [endOn, setEndOn] = useState("");
  const [source, setSource] = useState(""); const [destination, setDestination] = useState(""); const [error, setError] = useState("");
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["forecast-workspace"] });
  const save = useMutation({ mutationFn: async () => {
    const amountMinor = Number(parseDisplayAmountToMinor(amount)); if (!label.trim() || !startOn || amountMinor <= 0) throw new Error("Label, positive amount, and start date are required.");
    const payload = { kind, label: label.trim(), amount_minor: amountMinor, frequency, interval_count: intervalCount, start_on: startOn, end_on: endOn || null,
      day_of_week: frequency === "weekly" ? day : null, day_of_month: frequency === "weekly" ? null : day,
      source_account_id: kind === "income" ? null : source || null, destination_account_id: kind === "expense" ? null : destination || null };
    if (editingId) await recurringRepository.update(editingId, payload); else await recurringRepository.create(payload);
  }, onSuccess: () => { setEditingId(null); setLabel(""); setAmount(""); setError(""); void refresh(); }, onError: (reason) => setError(reason instanceof Error ? reason.message : "Rule could not be saved.") });
  const change = useMutation({ mutationFn: ({ id, active, archive }: { id: string; active?: boolean; archive?: boolean }) => archive ? recurringRepository.archive(id) : recurringRepository.setActive(id, Boolean(active)), onSuccess: () => void refresh() });
  function edit(id: string) { const rule = workspace.data?.rules.find((candidate) => candidate.id === id); if (!rule) return; setEditingId(id); setKind(rule.kind); setLabel(rule.label); setAmount((Number(rule.amount_minor) / 100).toFixed(2)); setFrequency(rule.frequency); setIntervalCount(rule.interval_count); setDay(rule.day_of_week ?? rule.day_of_month ?? 1); setStartOn(rule.start_on); setEndOn(rule.end_on ?? ""); setSource(rule.source_account_id ?? ""); setDestination(rule.destination_account_id ?? ""); }
  function submit(event: FormEvent) { event.preventDefault(); save.mutate(); }
  const currency = workspace.data?.profile.base_currency ?? "NOK"; const accounts = workspace.data?.accounts.filter((account) => !account.is_system) ?? [];
  return <Page eyebrow="Expected rhythm" title="Recurring rules" description="Create reusable income, expense, and transfer schedules. Runway expands them in memory and stores only exceptions such as skips, overrides, and matches.">
    <div className="forecast-layout"><section className="money-panel"><div className="panel-heading"><div><p className="section-kicker">Your schedules</p><h2>Recurring money</h2></div><strong>{workspace.data?.rules.length ?? 0}</strong></div>{workspace.isLoading ? <p className="muted">Loading recurring rules…</p> : null}<div className="recurring-list">{workspace.data?.rules.map((rule) => <article className={`recurring-row ${rule.active ? "" : "paused"}`} key={rule.id}><div><span className="rule-kind">{rule.kind}</span><h3>{rule.label}</h3><p>{describe(rule)}</p><strong>{formatMinorUnits(asMinorUnits(Number(rule.amount_minor)), currency)}</strong></div><div className="row-actions"><button onClick={() => edit(rule.id)}>Edit</button><button onClick={() => change.mutate({ id: rule.id, active: !rule.active })}>{rule.active ? "Pause" : "Resume"}</button><button onClick={() => change.mutate({ id: rule.id, archive: true })}>Archive</button></div></article>)}{!workspace.isLoading && !workspace.data?.rules.length ? <p className="muted">No recurring rules yet. Existing migrated one-offs remain unchanged.</p> : null}</div></section>
      <section className="money-panel"><div className="panel-heading"><div><p className="section-kicker">Schedule</p><h2>{editingId ? "Edit recurring rule" : "New recurring rule"}</h2></div></div><form className="money-form" onSubmit={submit}><label>Type<select value={kind} onChange={(event) => setKind(event.target.value as typeof kind)}><option value="income">Income</option><option value="expense">Expense</option><option value="transfer">Transfer</option></select></label><label>Label<input value={label} onChange={(event) => setLabel(event.target.value)} required/></label><label>Amount<input inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} required/></label><label>Repeats<select value={frequency} onChange={(event) => setFrequency(event.target.value as typeof frequency)}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label>Every<input type="number" min="1" max="120" value={intervalCount} onChange={(event) => setIntervalCount(Number(event.target.value))}/></label><label>{frequency === "weekly" ? "Day of week (0–6)" : "Day of month"}<input type="number" min={frequency === "weekly" ? 0 : 1} max={frequency === "weekly" ? 6 : 31} value={day} onChange={(event) => setDay(Number(event.target.value))}/></label><label>Starts<input type="date" value={startOn} onChange={(event) => setStartOn(event.target.value)} required/></label><label>Ends <span className="optional">optional</span><input type="date" value={endOn} onChange={(event) => setEndOn(event.target.value)}/></label>{kind !== "income" ? <label>From account<select required value={source} onChange={(event) => setSource(event.target.value)}><option value="">Choose account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label> : null}{kind !== "expense" ? <label>To account<select required value={destination} onChange={(event) => setDestination(event.target.value)}><option value="">Choose account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label> : null}{error ? <p className="field-error" role="alert">{error}</p> : null}<button className="primary-button" disabled={save.isPending}>{editingId ? "Save recurring rule" : "Create recurring rule"}</button>{editingId ? <button type="button" onClick={() => setEditingId(null)}>Cancel editing</button> : null}</form></section></div>
  </Page>;
}
